# Generated by Django 4.1 on 2022-11-01 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(default='default.jpg', upload_to='event_images')),
                ('event_type', models.CharField(max_length=20)),
                ('event_title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('schedule', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('url_image', models.TextField(default='/')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
