# Generated by Django 4.1 on 2022-11-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='event_images'),
        ),
    ]
