# Generated by Django 4.1 on 2022-12-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_image',
        ),
        migrations.RemoveField(
            model_name='events',
            name='url_image',
        ),
    ]
