# Generated by Django 4.1 on 2022-10-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
