# Generated by Django 4.1 on 2022-10-27 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_alter_project_current_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='liked_by',
            field=models.ManyToManyField(related_name='projects_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
