# Generated by Django 4.1 on 2022-10-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_donation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
    ]
