# Generated by Django 4.1 on 2022-10-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('news_title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('news_text', models.TextField()),
            ],
        ),
    ]
