# Generated by Django 4.1 on 2022-10-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitems',
            name='news_image',
        ),
    ]
