# Generated by Django 4.1 on 2022-10-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inforum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_job',
            field=models.CharField(default='Unemployed', max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
