# Generated by Django 4.1 on 2022-10-22 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inforum', '0002_alter_comment_time_created_alter_forum_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_created',
            field=models.DateField(default=datetime.datetime(2022, 10, 22, 8, 50, 7, 963428, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='time_created',
            field=models.DateField(default=datetime.datetime(2022, 10, 22, 8, 50, 7, 962426, tzinfo=datetime.timezone.utc)),
        ),
    ]
