# Generated by Django 4.1 on 2022-10-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_creator', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('course_time', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
