# Generated by Django 4.1 on 2022-12-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_url',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Course_detail',
        ),
    ]
