# Generated by Django 4.1 on 2022-10-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_normaluser_managers_normaluserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluserprofile',
            name='birth_date',
            field=models.DateField(default='1990-01-01'),
        ),
        migrations.AddField(
            model_name='normaluserprofile',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='normaluserprofile',
            name='job',
            field=models.CharField(default='Unemployed', max_length=50),
        ),
        migrations.AddField(
            model_name='normaluserprofile',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
